name: Deploy user service to Amazon ECS

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "*.md", ".github/**" ]

env:
  AWS_REGION: eu-west-1
  SERVICE_ECR: user-repo
  ECR_REPOSITORY: 849349795052.dkr.ecr.eu-west-1.amazonaws.com/luxe-ecommerce-user-repo
  ECS_SERVICE: luxe-ecommerce-user-prod-service
  ECS_CLUSTER: luxe-ecommerce-cluster
  ECS_TASK_DEFINITION_FAMILY: luxe-ecommerce-user-prod-task
  CONTAINER_NAME: luxe-ecommerce-user


permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Login (OIDC)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::849349795052:role/GitHubOIDC-Backend
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $ECR_REPOSITORY

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }} # Use Git Commit SHA for unique tagging
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT


      - name: Render new Task Definition
        id: render-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          # fetch the latest active revision from AWS
          task-definition-family: ${{ env.ECS_TASK_DEFINITION_FAMILY }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true