name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: eu-west-1                   # Set your AWS region
  SERVICE_ECR: user-repo           # Your Amazon ECR repo name
  ECR_REPOSITORY: 849349795052.dkr.ecr.eu-west-1.amazonaws.com/luxe-ecommerce-user-repo
  ECS_SERVICE: luxe-ecommerce-user-prod-service              # Your existing ECS service name
  ECS_CLUSTER: luxe-ecommerce-cluster          # Your existing ECS cluster name
  ECS_TASK_DEFINITION_FAMILY: luxe-ecommerce-user-prod-task  # Path to your task definition file
  CONTAINER_NAME: luxe-ecommerce-user            # Name of the container in the task definition


permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Login (OIDC)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::849349795052:role/GitHubOIDC-Backend
          aws-region: $AWS_REGION

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $ECR_REPOSITORY

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }} # Use Git Commit SHA for unique tagging
        run: |
          docker build -t $ECR_REPOSITORY/$SERVICE_ECR:$IMAGE_TAG .
          docker push $ECR_REPOSITORY/$SERVICE_ECR:$IMAGE_TAG
          echo "image=$ECR_REPOSITORY/$SERVICE_ECR:$IMAGE_TAG" >> $GITHUB_OUTPUT


      - name: Render new Task Definition
        id: render-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          # This tells the action to fetch the latest active revision from AWS
          task-definition-family: ${{ env.ECS_TASK_DEFINITION_FAMILY }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true





          
# uses: aws-actions/amazon-ecr-login@v2




      # - name: Fetch and Update Task Definition
      #   id: update-task-def
      #   with:
      #     task-definition: ${{ env.ECS_TASK_DEFINITION }}
      #     container-name: ${{ env.CONTAINER_NAME }}
      #     image: ${{ steps.build-image.outputs.image }}
      #   run: |
      #     ## Fetch the latest active revision for your task family
      #     aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION_FAMILY }} \
      #      --query 'taskDefinition' > task-def.json
          
      #     ## Use 'jq' to update the image in the containerDefinitions array and save json
      #     jq --arg IMAGE "${{ steps.build-image.outputs.image }}" \
      #        '(.containerDefinitions[] | select(.name=="${{ env.CONTAINER_NAME }}") | .image) = $IMAGE' \
      #        task-def.json > updated-task-def.json
          
      #     ## Clean the JSON (remove metadata that AWS won't accept in a new registration)
      #     jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)' \
      #        updated-task-def.json > final-task-def.json

      #     ## save new task definition as step output
      #     echo "task-definition=final-task-def.json" >> $GITHUB_OUTPUT

      # - name: Deploy Amazon ECS task definition
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      #   with:
      #     task-definition: final-task-def.json
      #     service: ${{ env.ECS_SERVICE }}
      #     cluster: ${{ env.ECS_CLUSTER }}
      #     wait-for-service-stability: true
          